### ISSUE TITLE
Building from source - tomcrypt fails to compile

### ISSUE THREAD

**Issue by mouse07410** [kpdemetriou/pqcrypto#2]
MacOS 10.15.6, Xcode-11.7, Python-3.8.5

```
$ python setup.py build
. . . . .
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -O3 -std=gnu17 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DHAVE_CONFIG_H -Isrc/ -Isrc/libtom/ -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/DES.c -o build/temp.macosx-10.15-x86_64-3.8/src/DES.o
In file included from src/DES.c:34:
In file included from src/libtom/tomcrypt_des.c:11:
In file included from src/libtom/tomcrypt.h:67:
src/libtom/tomcrypt_macros.h:269:25: error: constraint 'I' expects an integer constant expression
      :"0" (word), "I" (i));
                        ^
src/libtom/tomcrypt_macros.h:277:25: error: constraint 'I' expects an integer constant expression
      :"0" (word), "I" (i));
                        ^
src/libtom/tomcrypt_macros.h:368:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
src/libtom/tomcrypt_macros.h:376:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
In file included from src/DES.c:132:
src/block_template.c:791:79: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
        if (PCT_CounterBEType == NULL || PyType_Check((PyObject *)PCT_CounterBEType) < 0 ||
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
src/block_template.c:792:77: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
                 PCT_CounterLEType == NULL || PyType_Check((PyObject *)PCT_CounterLEType) < 0 ||
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
src/block_template.c:793:47: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
                 abiver == NULL || PyInt_CheckExact(abiver) < 0 || PyInt_AS_LONG(abiver) != PCT_CTR_ABI_VERSION)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
In file included from src/DES.c:34:
In file included from src/libtom/tomcrypt_des.c:11:
In file included from src/libtom/tomcrypt.h:68:
src/libtom/tomcrypt_cipher.h:546:3: warning: tentative array definition assumed to have one element
} cipher_descriptor[];
  ^
4 warnings and 4 errors generated.
error: command 'clang' failed with exit status 1
```

### Update

if you get past the above problem, the following occurs:
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -O3 -std=gnu17 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DHAVE_CONFIG_H -Isrc/ -Isrc/libtom/ -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/DES.c -o build/temp.macosx-10.15-x86_64-3.8/src/DES.o
In file included from src/DES.c:132:
src/block_template.c:791:79: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
        if (PCT_CounterBEType == NULL || PyType_Check((PyObject *)PCT_CounterBEType) < 0 ||
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
src/block_template.c:792:77: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
                 PCT_CounterLEType == NULL || PyType_Check((PyObject *)PCT_CounterLEType) < 0 ||
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
src/block_template.c:793:47: warning: result of comparison of constant 0 with boolean expression is always false [-Wtautological-constant-compare]
                 abiver == NULL || PyInt_CheckExact(abiver) < 0 || PyInt_AS_LONG(abiver) != PCT_CTR_ABI_VERSION)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
In file included from src/DES.c:34:
In file included from src/libtom/tomcrypt_des.c:11:
In file included from src/libtom/tomcrypt.h:68:
src/libtom/tomcrypt_cipher.h:546:3: warning: tentative array definition assumed to have one element
} cipher_descriptor[];
  ^
In file included from src/DES.c:34:
In file included from src/libtom/tomcrypt_des.c:11:
In file included from src/libtom/tomcrypt.h:67:
src/libtom/tomcrypt_macros.h:275:9: error: invalid operand for instruction
   asm ("rorl %2,%0"
        ^
<inline asm>:1:12: note: instantiated into assembly here
        rorl %edx,%r8d
                  ^~~~
In file included from src/DES.c:34:
In file included from src/libtom/tomcrypt_des.c:11:
In file included from src/libtom/tomcrypt.h:67:
src/libtom/tomcrypt_macros.h:275:9: error: invalid operand for instruction
   asm ("rorl %2,%0"
        ^
<inline asm>:1:12: note: instantiated into assembly here
        rorl %edi,%ebx
                  ^~~~
4 warnings and 2 errors generated.
error: command 'clang' failed with exit status 1
```

**Comment by mouse07410** [comment]
This might help you figure out what's wrong and how to fix it - after applying these and adding `-DLTC_NO_ROLC=1` to `CFLAGS` it compiles and passes (only) some tests:
```diff
diff --git a/lib/Crypto/Random/_UserFriendlyRNG.py b/lib/Crypto/Random/_UserFriendlyRNG.py
index 957e006..0e06d8c 100644
--- a/lib/Crypto/Random/_UserFriendlyRNG.py
+++ b/lib/Crypto/Random/_UserFriendlyRNG.py
@@ -74,7 +74,7 @@ class _EntropyCollector(object):
         self._time_es.feed(struct.pack("@I", int(2**30 * (t - floor(t)))))
 
         # Add the fractional part of time.clock()
-        t = time.clock()
+        t = time.clock_gettime(time.CLOCK_REALTIME)
         self._clock_es.feed(struct.pack("@I", int(2**30 * (t - floor(t)))))
 
 
diff --git a/lib/Crypto/SelfTest/Random/test_random.py b/lib/Crypto/SelfTest/Random/test_random.py
index 3e85c3c..bb8165d 100644
--- a/lib/Crypto/SelfTest/Random/test_random.py
+++ b/lib/Crypto/SelfTest/Random/test_random.py
@@ -104,8 +104,7 @@ class SimpleTest(unittest.TestCase):
         for i in range(10):
             self.assertEqual(random.choice((1,2,3)) in (1,2,3), True)
         self.assertEqual(random.choice([1,2,3]) in [1,2,3], True)
-        if sys.version_info[0] is 3:
-            self.assertEqual(random.choice(bytearray(b('123'))) in bytearray(b('123')), True)
+        self.assertEqual(random.choice(bytearray(b('123'))) in bytearray(b('123')), True)
         self.assertEqual(1, random.choice([1]))
         self.assertRaises(IndexError, random.choice, [])
         self.assertRaises(TypeError, random.choice, 1)
diff --git a/src/CAST.c b/src/CAST.c
index d7b00f3..00b3b2e 100644
--- a/src/CAST.c
+++ b/src/CAST.c
@@ -273,7 +273,7 @@ static void castschedulekeys(block_state *schedule, uint8 *key, int keybytes)
 
 static block_state sched;
 
-void encrypt(key, keylen, in, out)
+void CAST_encrypt(key, keylen, in, out)
        uint8 *key;
        int keylen;
        uint8 *in, *out;
@@ -296,7 +296,7 @@ void tst(key, keylen, data, result)
        uint8 d[8];
        int i;
     
-       encrypt(key, keylen, data, d);
+       CAST_encrypt(key, keylen, data, d);
     
        for(i = 0; i < 8; i++)
                if (d[i] != result[i])
diff --git a/src/libtom/tomcrypt_macros.h b/src/libtom/tomcrypt_macros.h
index 53bda9b..31f4a18 100644
--- a/src/libtom/tomcrypt_macros.h
+++ b/src/libtom/tomcrypt_macros.h
@@ -266,7 +266,7 @@ static inline unsigned ROLc(unsigned word, const int i)
 {
    asm ("roll %2,%0"
       :"=r" (word)
-      :"0" (word),"I" (i));
+      :"0" (word), "r" (i));
    return word;
 }
 
@@ -274,7 +274,7 @@ static inline unsigned RORc(unsigned word, const int i)
 {
    asm ("rorl %2,%0"
       :"=r" (word)
-      :"0" (word),"I" (i));
+      :"0" (word), "r" (i));
    return word;
 }
 
@@ -365,7 +365,7 @@ static inline unsigned long ROL64c(unsigned long word, const int i)
 {
    asm("rolq %2,%0"
       :"=r" (word)
-      :"0" (word),"J" (i));
+      :"0" (word), "r" (i));
    return word;
 }
 
@@ -373,7 +373,7 @@ static inline unsigned long ROR64c(unsigned long word, const int i)
 {
    asm("rorq %2,%0"
       :"=r" (word)
-      :"0" (word),"J" (i));
+      :"0" (word), "r" (i));
    return word;
 }
 
```

Test failure with Python-3.7:
```
$ python3.7 setup.py test
. . . . .
clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -L/opt/local/lib -O3 -std=gnu17 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DLTC_NO_ROLC -I/opt/local/include -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DHAVE_CONFIG_H build/temp.macosx-10.15-x86_64-3.7/src/_counter.o -o build/lib.macosx-10.15-x86_64-3.7/Crypto/Util/_counter.cpython-37m-darwin.so
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SelfTest: You can ignore the RandomPool_DeprecationWarning that follows.
...........EE...........................................
======================================================================
ERROR: test_getStrongPrime_randfunc_bogus (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception is raised if randfunc returns something bogus.
----------------------------------------------------------------------
TypeError: randfunc must return a string of random bytes

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/Util/test_number.py", line 321, in test_getStrongPrime_randfunc_bogus
    self.assertRaises(TypeError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
SystemError: PyEval_EvalFrameEx returned a result with an error set

======================================================================
ERROR: test_getStrongPrime_randfunc_exception (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception raised in randfunc is propagated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
Crypto.SelfTest.Util.test_number.MyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/Util/test_number.py", line 308, in test_getStrongPrime_randfunc_exception
    self.assertRaises(MyError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

----------------------------------------------------------------------
Ran 1891 tests in 9.570s

FAILED (errors=2)
Traceback (most recent call last):
  File "setup.py", line 510, in <module>
    core.setup(**kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 377, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.macosx-10.15-x86_64-3.7/Crypto/SelfTest/__init__.py", line 76, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1891 errors=2 failures=0>)
```

Test failure with Python-3.8:
```
$ python3.8 setup.py test
running test
running build
running build_py
running build_ext
running build_configure
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SelfTest: You can ignore the RandomPool_DeprecationWarning that follows.
..running test
running build
running build_py
running build_ext
running build_configure
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SelfTest: You can ignore the RandomPool_DeprecationWarning that follows.
..E........EE...........................................
======================================================================
ERROR: runTest (Crypto.SelfTest.Random.test__UserFriendlyRNG.RNGMultiprocessingForkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Random/test__UserFriendlyRNG.py", line 132, in runTest
    manager = multiprocessing.Manager()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

======================================================================
ERROR: test_getStrongPrime_randfunc_bogus (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception is raised if randfunc returns something bogus.
----------------------------------------------------------------------
TypeError: randfunc must return a string of random bytes

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 321, in test_getStrongPrime_randfunc_bogus
    self.assertRaises(TypeError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
SystemError: PyEval_EvalFrameEx returned a result with an error set

======================================================================
ERROR: test_getStrongPrime_randfunc_exception (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception raised in randfunc is propagated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
Crypto.SelfTest.Util.test_number.MyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 308, in test_getStrongPrime_randfunc_exception
    self.assertRaises(MyError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

----------------------------------------------------------------------
Ran 1891 tests in 8.407s

FAILED (errors=3)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ur20980/src/pycrypto/setup.py", line 510, in <module>
    core.setup(**kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/ur20980/src/pycrypto/setup.py", line 377, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/__init__.py", line 76, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1891 errors=3 failures=0>)
E........EE...........................................
======================================================================
ERROR: runTest (Crypto.SelfTest.Random.test__UserFriendlyRNG.RNGMultiprocessingForkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Random/test__UserFriendlyRNG.py", line 132, in runTest
    manager = multiprocessing.Manager()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

======================================================================
ERROR: test_getStrongPrime_randfunc_bogus (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception is raised if randfunc returns something bogus.
----------------------------------------------------------------------
TypeError: randfunc must return a string of random bytes

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 321, in test_getStrongPrime_randfunc_bogus
    self.assertRaises(TypeError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
SystemError: PyEval_EvalFrameEx returned a result with an error set

======================================================================
ERROR: test_getStrongPrime_randfunc_exception (Crypto.SelfTest.Util.test_number.FastmathTests)
Test that when getStrongPrime is called, an exception raised in randfunc is propagated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
Crypto.SelfTest.Util.test_number.MyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 308, in test_getStrongPrime_randfunc_exception
    self.assertRaises(MyError, number._fastmath.getStrongPrime, 512, randfunc=randfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/Util/test_number.py", line 307, in randfunc
    raise MyError
SystemError: <class 'Crypto.SelfTest.Util.test_number.MyError'> returned a result with an error set

----------------------------------------------------------------------
Ran 1891 tests in 17.207s

FAILED (errors=3)
Traceback (most recent call last):
  File "setup.py", line 510, in <module>
    core.setup(**kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 377, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.macosx-10.15-x86_64-3.8/Crypto/SelfTest/__init__.py", line 76, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1891 errors=3 failures=0>)```

**Comment by mouse07410** [comment]
Wrong repo. Darn... Sorry.
